### ISSUE TITLE
leveldb writes blocks occassionarily

### ISSUE THREAD

**Issue by cmumford** [google/leveldb#170]
Original [issue 164](https://code.google.com/p/leveldb/issues/detail?id=164) created by wuzuyang on 2013-05-03T06:55:01.000Z:

<b>What steps will reproduce the problem?</b>
1. download and compile leveldb-1.9.0
2. write a test program test.cpp(in attachment), which makes only Put() operations.
3. compile and run the test

<b>What is the expected output? What do you see instead?</b>

All write operations should be quick enougth(less than 100ms), there should not print any slow log.

Here the outputs:

nums: 1000
   83: slow log: 7151.075
  169: slow log:  106.461
  403: slow log:  393.466
  487: slow log:  112.986
  563: slow log:  117.801

the slowest write operation takes 7151.075 ms!

<b>What version of the product are you using? On what operating system?</b>

Linux xen05.wd.corp.qihoo.net 2.6.18-164.el5xen #&nbsp;1 SMP Thu Sep 3 04:03:03 EDT 2009 x86_64 x86_64 x86_64 GNU/Linux

<b>Please provide any additional information below.</b>

How to compile test.cpp: g++ test.cpp -I../leveldb-1.9.0/include ../leveldb-1.9.0/libleveldb.a -pthread
Run it: ./a.out

**Comment by bwzhang2011** [comment]
@cmumford, any update with such issue ? was it fixed in the latest version ?

**Comment by cmumford** [comment]
Still present in v1.19. Agreed, this is related to compaction, and is a current design limitation of leveldb. I haven't dug into the code far enough to determine how difficult it would be to unblock the log writing from the background compaction.

**Comment by woofyzhao** [comment]
You might be writing too fast. It's intended to block and wait the underlying compaction to complete in that case.

**Comment by varshneydevansh** [comment]
are there any little beginner-friendly issues from where I can start with? =)
