### ISSUE TITLE
Xcode 9 / Swift 4 warnings

### ISSUE THREAD

**Issue by saldous** [google/leveldb#510]
There are 3 warnings when building a project in Xcode 9 with Swift 4.

Two warnings are the same, for lines 274 and 275:
Possible misuse of comma operator here - Cast expression to void to silence warning

and on line 1350:
Code will never be executed

**Comment by ghowen** [comment]
I am getting the same warnings in Xcode 9 GM with a Swift 3.2 project.

**Comment by ghowen** [comment]
After the migration of the project to Swift 4, only the third warning (Code will never be executed) remains. The suggested solution is:

Pods/leveldb-library/db/version_set.cc:1349:7: Silence by adding parentheses to mark code as explicitly dead

**Comment by bojanstef** [comment]
Not impressed 😝  <sub><sub>(just kidding, keep up the good work!)</sub></sub>

![The only warning in my project :D](https://user-images.githubusercontent.com/5675392/30669160-1afff84e-9e12-11e7-8518-56ba8163d819.png)

**Comment by pwnall** [comment]
@bojanstef I think the warning above was fixed in https://github.com/google/leveldb/commit/02f43c0fcde39823830493503e8a3f72fed43d24 which removed the dead code. If I'm wrong, please comment and I'll reopen.

**Comment by Neney22** [comment]
I updated the pod and Im still getting the same warnings. @pwnall  any suggestions ?

**Comment by pwnall** [comment]
The pod is definitely not managed by this repository. To be honest, I'm roughly aware of what Cocoa Pods are, but don't really know how they're implemented. I suspect that the pod uses the latest stable release (1.20), and you'll have to tweak the pod definition to use the master branch.

If you point me to where the point is defined, I can take a look and try to formulate a suggestion. (Are pods still Ruby? If so, I should be able to understand quickly.)

**Comment by saldous** [comment]
The pod uses version 1.18.3

**Comment by pwnall** [comment]
@saldous That's really old. I don't have the bandwidth to research the pod situation on my own (sorry), but if you point me to the right repository or put me in touch with the right people, I can answer questions and may be able to help out.

**Comment by soroyv** [comment]
I had this issue as well but I just unlocked the file in Xcode and removed the dead code. The leveldb-library is one of the libraries used by Firebase, their documentation lists 1.18.3 as the current version.

https://cocoapods.org/?q=leveldb-library

**Comment by saldous** [comment]
You'll need to edit the Pod spec file. https://guides.cocoapods.org/making/specs-and-specs-repo.html. But as @soroyv just noted, I ended up with levelDB via using Firebase, and Firebase's spec file points to levelDB v1.18.3.

**Comment by abigailyuan** [comment]
Same issue here. And I'm getting errors saying "stdint.h" should only be included when compiling with MSVC.

**Comment by boonieapps** [comment]
any word on a fix? I'm new to coding and i saw that soroyv said he deleted the code. line 1350 is my issue as well but not sure how much to delete.

**Comment by saldous** [comment]
Looks like the pod is now version 1.20 👍

**Comment by musso** [comment]
but Firebase still using leveldb 1.8
